### ISSUE TITLE
Seems broken

### ISSUE THREAD

**Issue by nathan-nz** [pfaffman/import-user-fields-from-csv#1]
When I run the script I get the following error. This occurs with both a complex .csv and a dead simple single record test file.

```
root@forumhinz-web-only:/var/www/discourse# rake user_fields:import_csv["/shared/import-test.csv"]
rake aborted!
SyntaxError: /var/www/discourse/lib/tasks/user_fields.rake:7: syntax error, unexpected '<'
<!DOCTYPE html>
^
/var/www/discourse/lib/tasks/user_fields.rake:8: syntax error, unexpected '<'
<html lang="en" data-color-mod...
^
/var/www/discourse/lib/tasks/user_fields.rake:8: syntax error, unexpected local variable or method, expecting end-of-input
<html lang="en" data-color-mode="auto" data-light...
                ^~~~
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/railties-7.0.2.4/lib/rails/engine.rb:661:in `block in run_tasks_blocks'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/railties-7.0.2.4/lib/rails/engine.rb:661:in `each'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/railties-7.0.2.4/lib/rails/engine.rb:661:in `run_tasks_blocks'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/railties-7.0.2.4/lib/rails/application.rb:505:in `run_tasks_blocks'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/railties-7.0.2.4/lib/rails/engine.rb:464:in `load_tasks'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/railties-7.0.2.4/lib/rails/railtie.rb:224:in `public_send'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/railties-7.0.2.4/lib/rails/railtie.rb:224:in `method_missing'
/var/www/discourse/Rakefile:9:in `<main>'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
```
The test file:

> user_id | user_field_20
> -- | --
> 7875 | Super Test

**Comment by nathan-nz** [comment]
Actually, I managed to corrupt the script and turn it into a HTML file. Nice, eh?

**Comment by pfaffman** [comment]
OMG. So glad you figured this one out. I was going to be completely stumped.
